on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/dev'
    environment: dev 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "msg: $msg"

  # Plan_Main:
  #   if: github.ref == 'refs/heads/main'
  #     environment: main
    # runs-on: ubuntu-latest
    # steps:
    #   - run: |
    #       echo "msg: $msg"

        # env:
        #   LEVEL: ${{ inputs.logLevel }}
        #   TAGS: ${{ inputs.tags }}
        #   ENVIRONMENT: ${{ inputs.environment }}

  # plan_main:
  #   if: github.ref == 'refs/heads/main'
  #   with: 
  #     env: 
  #       msg: ${{ vars.$msg }}
  #   environment: main
  #   #runs-on: ubuntu-latest
  #   steps:
  #     - name: run env
  #       run: echo $msg
