on:
  workflow_dispatch:
    inputs:
      calledworkflow_name: 
        description: " called workflow name for triggaring "
        required: true 
        default: "calledworkflow"

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    environment: main
    runs-on: ubuntu-latest
    steps:
      - run: ${{ vars.msg }}
      - name: check ip
        run: |
          agentIP=$(curl https:/api.ipify.org/)
          echo $agentIP
      - name: check ip2
        run: |
          agentIP=(curl -s https:/api.ipify.org/)
          echo $agentIP
      - name: githubrunner
        uses: azure@CLI@v1
          with: 
            inlineScript: |
              set -eu 
              agentIP=$(curl https:/api.ipify.org)
  # Plan_Main:
  #   if: github.ref == 'refs/heads/main'
  #     environment: main
    # runs-on: ubuntu-latest
    # steps:
    #   - run: |
    #       echo "msg: $msg"

        # env:
        #   LEVEL: ${{ inputs.logLevel }}
        #   TAGS: ${{ inputs.tags }}
        #   ENVIRONMENT: ${{ inputs.environment }}

  # plan_main:
  #   if: github.ref == 'refs/heads/main'
  #   with: 
  #     env: 
  #       msg: ${{ vars.$msg }}
  #   environment: main
  #   #runs-on: ubuntu-latest
  #   steps:
  #     - name: run env
  #       run: echo $msg
