on:
  workflow_dispatch:

jobs:
  plan_dev:
    if: github.ref == 'refs/heads/dev'
    with: 
      env: 
        msg: ${{ vars.$msg }}
    environment: dev
    #runs-on: ubuntu-latest
    steps:
      - name: run env
        run: echo $msg

  plan_main:
    if: github.ref == 'refs/heads/main'
    with: 
      env: 
        msg: ${{ vars.$msg }}
    environment: main
    #runs-on: ubuntu-latest
    steps:
      - name: run env
        run: echo $msg
